"""SQL-free repository protocols for durable reproduction state."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from backend.app.domain.persistence import (
    AuthoritativePlanningSnapshot,
    PersistedComparisonReport,
    PersistedFinalResult,
    ReproductionJob,
    ReproductionJobStatus,
    ResultValidationStatus,
)
from backend.app.domain.product_events import ReproductionEvent, ReproductionEventType, ReproductionIntake
from backend.app.domain.session import ReproductionSession
from backend.app.orchestration.ports import ReproductionRunRepository
from .job_queue import DurableJobQueue
from .external_resources import ResourceRegistry


class PersistenceEntityNotFoundError(LookupError):
    pass


class PersistenceConflictError(RuntimeError):
    pass


@runtime_checkable
class ReproductionJobRepository(Protocol):
    def create(self, job: ReproductionJob) -> None: ...
    def get(self, job_id: str) -> ReproductionJob: ...
    def update(self, job: ReproductionJob) -> None: ...
    def list(self, *, status: ReproductionJobStatus | None = None) -> tuple[ReproductionJob, ...]: ...
    def list_by_owner(self, owner_principal: str) -> tuple[ReproductionJob, ...]: ...
    def list_by_session(self, session_id: str) -> tuple[ReproductionJob, ...]: ...


@runtime_checkable
class ReproductionSessionRepository(Protocol):
    def create(self, session: ReproductionSession) -> None: ...
    def get(self, session_id: str) -> ReproductionSession: ...
    def get_by_intake(self, intake_id: str) -> ReproductionSession | None: ...
    def update(self, session: ReproductionSession) -> None: ...
    def list_by_owner(self, owner_principal: str) -> tuple[ReproductionSession, ...]: ...


@runtime_checkable
class ReproductionIntakeRepository(Protocol):
    def create(self, intake: ReproductionIntake) -> None: ...
    def get(self, intake_id: str) -> ReproductionIntake: ...
    def update(self, intake: ReproductionIntake) -> None: ...
    def list_by_owner(self, owner_principal: str) -> tuple[ReproductionIntake, ...]: ...


@runtime_checkable
class ReproductionEventRepository(Protocol):
    def append(
        self, *, intake_id: str, owner_principal: str,
        event_type: ReproductionEventType, payload: dict,
        job_id: str | None = None, session_id: str | None = None,
    ) -> ReproductionEvent: ...
    def list_by_intake(self, intake_id: str, *, after_sequence: int = 0) -> tuple[ReproductionEvent, ...]: ...
    def list_by_job(self, job_id: str, *, after_sequence: int = 0) -> tuple[ReproductionEvent, ...]: ...
    def list_by_session(self, session_id: str, *, after_sequence: int = 0) -> tuple[ReproductionEvent, ...]: ...
    def bind_job(self, intake_id: str, job_id: str) -> None: ...
    def bind_session(self, intake_id: str, session_id: str) -> None: ...


@runtime_checkable
class PlanningSnapshotRepository(Protocol):
    def create(self, snapshot: AuthoritativePlanningSnapshot) -> None: ...
    def get(self, snapshot_id: str) -> AuthoritativePlanningSnapshot: ...
    def get_by_job(self, job_id: str) -> AuthoritativePlanningSnapshot: ...
    def get_by_plan(self, plan_id: str) -> AuthoritativePlanningSnapshot: ...


@runtime_checkable
class FinalResultRepository(Protocol):
    def create(self, result: PersistedFinalResult) -> None: ...
    def get(self, result_id: str) -> PersistedFinalResult: ...
    def update_validation(self, result_id: str, status: ResultValidationStatus) -> PersistedFinalResult: ...
    def list_by_job(self, job_id: str) -> tuple[PersistedFinalResult, ...]: ...
    def list_by_run(self, run_id: str) -> tuple[PersistedFinalResult, ...]: ...


@runtime_checkable
class ComparisonReportRepository(Protocol):
    def create(self, report: PersistedComparisonReport) -> None: ...
    def get(self, report_id: str) -> PersistedComparisonReport: ...
    def update(self, report: PersistedComparisonReport) -> None: ...
    def list_by_job(self, job_id: str) -> tuple[PersistedComparisonReport, ...]: ...


@runtime_checkable
class PersistenceUnitOfWork(Protocol):
    intakes: ReproductionIntakeRepository
    sessions: ReproductionSessionRepository
    events: ReproductionEventRepository
    jobs: ReproductionJobRepository
    planning_snapshots: PlanningSnapshotRepository
    runs: ReproductionRunRepository
    final_results: FinalResultRepository
    comparisons: ComparisonReportRepository
    queue: DurableJobQueue
    resources: ResourceRegistry

    def __enter__(self) -> "PersistenceUnitOfWork": ...
    def __exit__(self, exc_type, exc, traceback) -> bool: ...
