"""Pure PaperReproAgent domain models."""

from .experiment import (
    AgentEventPayload,
    Artifact,
    ArtifactKind,
    DatasetSource,
    EnvironmentSpecification,
    EventType,
    ExperimentRun,
    ExperimentSpecification,
    ExperimentTaskType,
    LogPayload,
    Metric,
    MetricExpectation,
    RepositorySource,
    ResourceRequest,
    RunError,
    RunEvent,
    RunRequest,
    RunResult,
    RunStartedPayload,
    RunStatus,
    RunTerminalPayload,
    RuntimeOptions,
    StatusChangedPayload,
)
from .reproduction import (
    AblationDefinition,
    EvidenceReference,
    EvidenceSourceType,
    InformationStatus,
    PaperClaim,
    PaperReference,
    PaperSourceType,
    ReproductionParameter,
    ReproductionSpecification,
    ReproductionTarget,
    TargetType,
)
from .paper import (
    BoundingBox,
    ContentBlock,
    ContentBlockType,
    FigureBlock,
    PageBlock,
    PaperDocument,
    ParseMetadata,
    ParseStatus,
    SectionBlock,
    TableBlock,
    TableData,
)
from .intelligence import (
    CatalogEntity, ConflictCandidate, ConflictStatus, ConflictType,
    ExperimentType, ExtractionConflict, ExtractionMetadata, ExtractionStatus,
    ExtractionTrace, FigureObservation, GoalResolutionResult,
    GoalResolutionStatus, PaperExperimentCatalog, PaperExperimentRecord,
    UserReproductionGoal,
)

__all__ = [
    "AblationDefinition",
    "BoundingBox",
    "ContentBlock",
    "ContentBlockType",
    "AgentEventPayload",
    "Artifact",
    "ArtifactKind",
    "DatasetSource",
    "EnvironmentSpecification",
    "EvidenceReference",
    "EvidenceSourceType",
    "EventType",
    "ExperimentRun",
    "ExperimentSpecification",
    "ExperimentTaskType",
    "InformationStatus",
    "FigureBlock",
    "LogPayload",
    "Metric",
    "MetricExpectation",
    "PaperClaim",
    "PaperDocument",
    "PageBlock",
    "PaperReference",
    "PaperSourceType",
    "ParseMetadata",
    "ParseStatus",
    "RepositorySource",
    "ReproductionParameter",
    "ReproductionSpecification",
    "ReproductionTarget",
    "ResourceRequest",
    "RunError",
    "RunEvent",
    "RunRequest",
    "RunResult",
    "RunStartedPayload",
    "RunStatus",
    "RunTerminalPayload",
    "RuntimeOptions",
    "SectionBlock",
    "StatusChangedPayload",
    "TargetType",
    "TableBlock",
    "TableData",
    "CatalogEntity",
    "ConflictCandidate",
    "ConflictStatus",
    "ConflictType",
    "ExperimentType",
    "ExtractionConflict",
    "ExtractionMetadata",
    "ExtractionStatus",
    "ExtractionTrace",
    "FigureObservation",
    "GoalResolutionResult",
    "GoalResolutionStatus",
    "PaperExperimentCatalog",
    "PaperExperimentRecord",
    "UserReproductionGoal",
]
