"""Pure PaperReproAgent domain models."""

from .experiment import (
    AgentEventPayload,
    CommandEventPayload,
    Artifact,
    ArtifactKind,
    CheckpointPolicy,
    DatasetSource,
    EnvironmentSpecification,
    EnvironmentRequirement,
    ExecutableCommand,
    EventType,
    ExperimentRun,
    ExperimentAction,
    ExperimentActionPlan,
    ExperimentActionType,
    ExperimentSpecification,
    ExperimentTaskType,
    LogPayload,
    PatchEventPayload,
    PlanEventPayload,
    Metric,
    MetricDirection,
    MetricExpectation,
    EvaluationPolicy,
    EvaluationPolicyConfidence,
    EvaluationPolicySource,
    FinalMetric,
    FinalMetricStatus,
    FinalResult,
    ResultAggregation,
    RunFinalResult,
    DatasetAvailability,
    DatasetRequirement,
    RepositorySource,
    ResourceRequest,
    ResourceRequirement,
    RunError,
    RunEvent,
    RunRequest,
    RunResult,
    RunStartedPayload,
    RunStatus,
    RunTerminalPayload,
    RuntimeOptions,
    StatusChangedPayload,
    ValidationEventPayload,
)
from .reproduction import (
    AblationDefinition,
    EvidenceReference,
    EvidenceSourceType,
    InformationStatus,
    PaperClaim,
    PaperReference,
    PaperSourceType,
    ReproductionParameter,
    ReproductionSpecification,
    ReproductionTarget,
    TargetType,
)
from .paper import (
    BoundingBox,
    ContentBlock,
    ContentBlockType,
    FigureBlock,
    PageBlock,
    PaperDocument,
    ParseMetadata,
    ParseStatus,
    SectionBlock,
    TableBlock,
    TableData,
)
from .intelligence import (
    CatalogEntity, ConflictCandidate, ConflictStatus, ConflictType,
    ExperimentSelection, ExperimentType, ExtractionConflict, ExtractionMetadata, ExtractionStatus,
    ExtractionTrace, FigureObservation, GoalResolutionResult,
    GoalResolutionStatus, PaperExperimentCatalog, PaperExperimentRecord,
    SelectionMode, UserReproductionGoal,
)
from .repository import (
    CliArgument,CodeIndex,CodeSymbol,DependencyRecord,EntrypointCandidate,EntrypointType,GitLfsPointer,
    RepositoryAnalysisCatalog,RepositoryAnalysisMetadata,RepositoryAnalysisStatus,RepositoryAnalysisTrace,
    RepositoryCommand,RepositoryComponentRecord,RepositoryConfigRecord,RepositoryConflict,
    RepositoryConflictCandidate,RepositoryConflictStatus,RepositoryConflictType,RepositoryEvaluationPolicyRecord,RepositoryExperimentImplementation,
    RepositoryFact,RepositoryFile,RepositoryFileType,RepositoryReference,RepositorySnapshot,
    RepositorySnapshotMetadata,RepositorySourceType,SubmodulePolicy,SubmoduleRecord,SymbolKind,
)
from .alignment import (
    AblationAlignment,AlignmentAmbiguity,AlignmentAnalysisStatus,AlignmentConflict,AlignmentConflictCandidate,
    AlignmentConflictStatus,AlignmentConflictType,AlignmentItemSource,AlignmentMetadata,AlignmentStatus,AlignmentTrace,
    DatasetAlignment,EvaluationPolicyAlignment,EvaluationPolicyAlignmentStatus,ExperimentAlignmentRecord,MetricAlignment,ModelAlignment,PaperCodeAlignmentCatalog,
    ParameterAlignment,ParameterMappingStatus,UnmatchedAlignmentItem,
)
from .comparison import (
    ComparisonEvidenceChain, ComparisonPolicyKind, ExecutionFailureReference,
    ExperimentComparison, ExperimentComparisonStatus, MetricComparison,
    MetricComparisonPolicy, MetricComparisonStatus, MetricIdentity,
    ReproductionComparisonReport,
)
from .planner import (
    BlockerSeverity,DecisionSource,ExperimentDependency,PlanBlocker,PlanningMetadata,PlanningOverrides,
    PlanningTrace,PlannerDecision,PlanStatus,ReproductionExecutionPlan,ReproductionPolicy,UnresolvedPlanItem,
)
from .reproduction_run import (
    ArtifactReference, AttemptRecord, AttemptStatus, FailureCategory, FailureRecord,
    PatchRecord, PatchStatus, ReproductionRun, RunManifest, StepRun, StepStatus,
    ValidationPhase, ValidationRecord,
)

__all__ = [
    "AblationDefinition",
    "BoundingBox",
    "ContentBlock",
    "ContentBlockType",
    "AgentEventPayload",
    "CommandEventPayload",
    "Artifact",
    "ArtifactKind",
    "CheckpointPolicy",
    "DatasetSource",
    "EnvironmentSpecification",
    "EnvironmentRequirement","ExecutableCommand",
    "EvidenceReference",
    "EvidenceSourceType",
    "EventType",
    "ExperimentRun",
    "ExperimentAction","ExperimentActionPlan","ExperimentActionType",
    "ExperimentSpecification",
    "ExperimentTaskType",
    "InformationStatus",
    "FigureBlock",
    "LogPayload",
    "PatchEventPayload","PlanEventPayload",
    "Metric",
    "MetricDirection",
    "MetricExpectation",
    "EvaluationPolicy","EvaluationPolicyConfidence","EvaluationPolicySource","FinalMetric","FinalMetricStatus","FinalResult","ResultAggregation","RunFinalResult",
    "DatasetAvailability","DatasetRequirement",
    "PaperClaim",
    "PaperDocument",
    "PageBlock",
    "PaperReference",
    "PaperSourceType",
    "ParseMetadata",
    "ParseStatus",
    "RepositorySource",
    "ReproductionParameter",
    "ReproductionSpecification",
    "ReproductionTarget",
    "ResourceRequest",
    "ResourceRequirement",
    "RunError",
    "RunEvent",
    "RunRequest",
    "RunResult",
    "RunStartedPayload",
    "RunStatus",
    "RunTerminalPayload",
    "RuntimeOptions",
    "SectionBlock",
    "StatusChangedPayload",
    "ValidationEventPayload",
    "TargetType",
    "TableBlock",
    "TableData",
    "CatalogEntity",
    "ConflictCandidate",
    "ConflictStatus",
    "ConflictType",
    "ExperimentSelection",
    "ExperimentType",
    "ExtractionConflict",
    "ExtractionMetadata",
    "ExtractionStatus",
    "ExtractionTrace",
    "FigureObservation",
    "GoalResolutionResult",
    "GoalResolutionStatus",
    "PaperExperimentCatalog",
    "PaperExperimentRecord",
    "SelectionMode",
    "UserReproductionGoal",
    "CliArgument","CodeIndex","CodeSymbol","DependencyRecord","EntrypointCandidate","EntrypointType","GitLfsPointer",
    "RepositoryAnalysisCatalog","RepositoryAnalysisMetadata","RepositoryAnalysisStatus","RepositoryAnalysisTrace",
    "RepositoryCommand","RepositoryComponentRecord","RepositoryConfigRecord","RepositoryConflict",
    "RepositoryConflictCandidate","RepositoryConflictStatus","RepositoryConflictType","RepositoryEvaluationPolicyRecord","RepositoryExperimentImplementation",
    "RepositoryFact","RepositoryFile","RepositoryFileType","RepositoryReference","RepositorySnapshot",
    "RepositorySnapshotMetadata","RepositorySourceType","SubmodulePolicy","SubmoduleRecord","SymbolKind",
    "AblationAlignment","AlignmentAmbiguity","AlignmentAnalysisStatus","AlignmentConflict","AlignmentConflictCandidate",
    "AlignmentConflictStatus","AlignmentConflictType","AlignmentItemSource","AlignmentMetadata","AlignmentStatus","AlignmentTrace",
    "DatasetAlignment","EvaluationPolicyAlignment","EvaluationPolicyAlignmentStatus","ExperimentAlignmentRecord","MetricAlignment","ModelAlignment","PaperCodeAlignmentCatalog",
    "ParameterAlignment","ParameterMappingStatus","UnmatchedAlignmentItem",
    "BlockerSeverity","DecisionSource","ExperimentDependency","PlanBlocker","PlanningMetadata","PlanningOverrides",
    "PlanningTrace","PlannerDecision","PlanStatus","ReproductionExecutionPlan","ReproductionPolicy","UnresolvedPlanItem",
    "ArtifactReference","AttemptRecord","AttemptStatus","FailureCategory","FailureRecord",
    "PatchRecord","PatchStatus","ReproductionRun","RunManifest","StepRun","StepStatus",
    "ValidationPhase","ValidationRecord",
    "ComparisonEvidenceChain","ComparisonPolicyKind","ExecutionFailureReference",
    "ExperimentComparison","ExperimentComparisonStatus","MetricComparison",
    "MetricComparisonPolicy","MetricComparisonStatus","MetricIdentity","ReproductionComparisonReport",
]
